### ISSUE TITLE
Max FPS not honouring the URL parameter with 5.1 and not working at all with 5.0

### ISSUE THREAD

**Issue by dan-tw** [EpicGames/PixelStreamingInfrastructure-archived-2024#100]
On the settings panel under `WebRTC` there is a `Max FPS` setting. If value in the panel is changed, it appends a parameter to the URL e.g. http://localhost/?WebRTCFPS=30

Using UE 5.1
- Visiting the frontend URL with the `?WebRTCFPS=30` parameter **_does not_** update the Max FPS in the Information panel.
- Changing the Max FPS in the WebRTC section on the Settings panel **_does_** update the MaxFPS in the Information panel.

Using UE 5.0, Max FPS just **does not seem to work at all**

**Comment by Belchy06** [comment]
I've got an idea of what's happening with this one.

I think what's happening is we're setting the FPS to what ever is in the URL. Updating this does nothing as when first run we currently don't have a stream.

User starts a stream, and will receive the initial settings object which updates all of WebRTC and encoder settings.

The callbacks on these settings are set to send their new value to UE so we end up just setting them back to whatever the application send us in the first place.

**Comment by lukehb** [comment]
@MWillWallT Is this fixed now, I think it is?

**Comment by MWillWallT** [comment]
@lukehb I've tested this, unfortunately the issues are still present. 
5.1 doesn't update the FPS in the info panel with the URL /?WebRTCFPS=30. As reported though changing it via the control panel does work. This was tested with the 5.1 Infra and latest 5.1.

I'm currently in the process of pulling 5.0 to test that.

**Comment by Belchy06** [comment]
It's a frontend specific issue. Will still happen with 5.0

**Comment by lukehb** [comment]
Is it fixed in the UE 5.2 branch of the infra. If so, we can backport.

**Comment by Belchy06** [comment]
This was tested using latest frontend version. Pretty sure we didn't support setting WebRTC settings in the URL with the old JS monolith, which is why it's popped up now.

**Comment by lukehb** [comment]
Fixed in https://github.com/EpicGames/PixelStreamingInfrastructure/commit/1695df21ba38765f951e00e8a242c431f381c26c
